/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.PrestamoLogica;
import modelo.Prestamo;

/**
 *
 * @author Usuario
 */
public class ConsultaPrestamos extends javax.swing.JPanel {

    vistaLogin frame;
    DefaultTableModel modelo;
    private Prestamo prestamo;
    private List<Prestamo> listaPrestamos;
     private PrestamoLogica prestamoLogica;
    
    public ConsultaPrestamos(vistaLogin frame) {
        this.frame = frame;
        listaPrestamos = new ArrayList<Prestamo>();
        prestamoLogica = new PrestamoLogica(); 
       
        initComponents();
        setBackground(Color.white);
        asignaturaComboBox.removeAllItems();
        asignaturaComboBox.addItem("NINGUNA");
        asignaturaComboBox.addItem("PRACTICA LIBRE");
        asignaturaComboBox.addItem("INTRODUCCION A LA TECNOLOGIA ELECTRONICA");
        asignaturaComboBox.addItem("ELECTRICIDAD PARA ELECTRONICA");
        asignaturaComboBox.addItem("CALCULO I");
        asignaturaComboBox.addItem("CALCULO II");
        asignaturaComboBox.addItem("FISICA");
        asignaturaComboBox.addItem("ELECTRONICA BASICA");
        asignaturaComboBox.addItem("ALGORITMIA Y PROGRAMACION");
        asignaturaComboBox.addItem("TECNICAS DIGITALES");
        asignaturaComboBox.addItem("FUENTES Y AMPLIFICADORES");
        asignaturaComboBox.addItem("CIRCUITOS INTEGRADOS");
        asignaturaComboBox.addItem("MATEMATICAS ESPECIALES");
        asignaturaComboBox.addItem("MEDICIONES ELECTRONICAS");
        asignaturaComboBox.addItem("SISTEMAS ELECTROMECANICOS");
        asignaturaComboBox.addItem("MICROPROCESADORE I");
        asignaturaComboBox.addItem("MICROPROCESADORES II");
        asignaturaComboBox.addItem("SISTEMAS DE COMUNICACIONES");
        asignaturaComboBox.addItem("SISTEMAS AUTOMATICOS DE CONTROL");
        asignaturaComboBox.addItem("CONTROL ELECTRONICO DE POTENCIA");
        asignaturaComboBox.addItem("PLC");
        asignaturaComboBox.addItem("INTRUMENTACION ELECTRONICA");
        asignaturaComboBox.addItem("EXPERIMENTACION FISICA I");
        asignaturaComboBox.addItem("EXPERIMENTACION FISICA II");
        asignaturaComboBox.addItem("LAB FISICA GENERAL I");
        asignaturaComboBox.addItem("LAB FISICA GENERAL II");
    }
    
  public void llenarTablaPrestamos(List<Prestamo> listPrestamos){
        
        List<Prestamo> listaPres;
        listaPres = listPrestamos;
        setTabla(listaPres);
    }

    public void setTabla(List<Prestamo> prestamos){
        modelo =  (DefaultTableModel) PrestamosTabla.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< prestamos.size();j++){
            aux = new String[14];
            aux[0] = String.valueOf(prestamos.get(j).getPrestamoID());
            aux[1] = String.valueOf(prestamos.get(j).getEquipoID().getEquipoID());
            aux[2] = prestamos.get(j).getEquipoID().getDescripcion();
            
            aux[3] = String.valueOf(prestamos.get(j).getUsuarioID().getUsuarioID());
            aux[4] = prestamos.get(j).getUsuarioID().getNombreUsuario();
            
            
            aux[5] = prestamos.get(j).getFechaEntrega().toString();
            aux[6] = prestamos.get(j).getHoraEntrega();
            try{
                aux[7] = prestamos.get(j).getFechaDevolucion().toString();
            }catch(Exception e){
                aux[7] = "No fecha";
            }
            aux[8] = prestamos.get(j).getHoraDevolucion();
            aux[9] = prestamos.get(j).getNombreMonitorAtendio();
            aux[10] = prestamos.get(j).getNombreMonitorDevolvio();
            aux[11] = prestamos.get(j).getEstadoPrestamo();
            aux[12] = prestamos.get(j).getObservaciones();
            aux[13] = prestamos.get(j).getAsignatura();
            modelo.addRow(aux);
        }
    }        

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrestamosTabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        botonConsultarTodos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonConsultarPendientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        asignaturaComboBox = new javax.swing.JComboBox();
        botonBorrarTodo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoCantidadRegistros = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("GIPLE V2.0 - LABORATORIO DE ELECTRÓNICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("CONSULTA DE PRESTAMOS DE GENERAL");

        PrestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Prestamo", "ID Equipo", "Nombre", "ID Usuario", "Nombre", "Fecha Entrega", "Hora Entrega", "Fecha Devol", "Hora Devol", "Atendio ", "Devolvio a", "Estado", "Observaciones", "Asignatura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PrestamosTabla);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Consultar Todos:");

        botonConsultarTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarTodos.setText("Consultar");
        botonConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarTodosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Consultar Pendientes:");

        botonConsultarPendientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarPendientes.setText("Consultar");
        botonConsultarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarPendientesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Asignatura:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Filtrar por:");

        asignaturaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonBorrarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrarTodo.setText("Borrar Todo");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Registros encontrados:");

        botonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonConsultarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(botonConsultarPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asignaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(botonConsultarTodos)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(asignaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultarPendientes)
                    .addComponent(jLabel4)
                    .addComponent(campoCantidadRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(botonBorrarTodo))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        frame.swap(1); // hace el llamado al panel de administracion
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarTodosActionPerformed
        listaPrestamos.removeAll(listaPrestamos);
        listaPrestamos = prestamoLogica.listarPrestamosporAsignatura(asignaturaComboBox.getSelectedItem().toString());
        llenarTablaPrestamos(listaPrestamos);
        campoCantidadRegistros.setText(String.valueOf(listaPrestamos.size()));
    }//GEN-LAST:event_botonConsultarTodosActionPerformed

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed
        listaPrestamos.removeAll(listaPrestamos);
        llenarTablaPrestamos(listaPrestamos);
        campoCantidadRegistros.setText("");
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void botonConsultarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarPendientesActionPerformed
        listaPrestamos.removeAll(listaPrestamos);
        listaPrestamos = prestamoLogica.listarPrestamosporAsignaturaPendientes(asignaturaComboBox.getSelectedItem().toString());
        llenarTablaPrestamos(listaPrestamos);
        campoCantidadRegistros.setText(String.valueOf(listaPrestamos.size()));
    }//GEN-LAST:event_botonConsultarPendientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrestamosTabla;
    private javax.swing.JComboBox asignaturaComboBox;
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonConsultarPendientes;
    private javax.swing.JButton botonConsultarTodos;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoCantidadRegistros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
