/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.EquipoLogica;
import logica.PrestamoLogica;
import modelo.Equipo;
import modelo.Prestamo;

/**
 *
 * @author Usuario
 */
public class consultarEquiposPanel extends javax.swing.JPanel {

    vistaLogin frame;
    EquipoLogica equipoLogica;
    DefaultTableModel modelo;
    private Prestamo prestamo;
    private List<Prestamo> listaPrestamos;
    private PrestamoLogica prestamoLogica;   
    
    public consultarEquiposPanel(vistaLogin frame) {
        this.frame = frame;
        equipoLogica = new EquipoLogica();
        listaPrestamos = new ArrayList<Prestamo>();
        prestamoLogica = new PrestamoLogica(); 
        initComponents();
        setBackground(Color.white);
    }
    
  public void llenarTablaPrestamos(List<Prestamo> listPrestamos){
        
        List<Prestamo> listaPres;
        listaPres = listPrestamos;
        setTabla(listaPres);
    }

    public void setTabla(List<Prestamo> prestamos){
        modelo =  (DefaultTableModel) PrestamosTabla.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< prestamos.size();j++){
            aux = new String[12];
            aux[0] = String.valueOf(prestamos.get(j).getPrestamoID());
            aux[1] = String.valueOf(prestamos.get(j).getUsuarioID().getUsuarioID());
            aux[2] = prestamos.get(j).getUsuarioID().getNombreUsuario();
            aux[3] = prestamos.get(j).getFechaEntrega().toString();
            aux[4] = prestamos.get(j).getHoraEntrega();
             try{
                aux[5] = prestamos.get(j).getFechaDevolucion().toString();
            }catch(Exception e){
                aux[5] = "No fecha";
            }
            aux[6] = prestamos.get(j).getHoraDevolucion();
            aux[7] = prestamos.get(j).getNombreMonitorAtendio();
            aux[8] = prestamos.get(j).getNombreMonitorDevolvio();
            aux[9] = prestamos.get(j).getEstadoPrestamo();
            aux[10] = prestamos.get(j).getObservaciones();
            aux[11] = prestamos.get(j).getAsignatura();
            modelo.addRow(aux);
        }
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrestamosTabla = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoEquipoID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoHorasUso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoFechaIngreso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoRevision = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("GIPLE V2.0 - LABORATORIO DE ELECTRÓNICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("CONSULTA DE EQUIPOS");

        PrestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Prestamo", "ID Usuario", "Nombre", "Fecha Entrega", "Hora Entrega", "Fecha Devol", "Hora Devol", "Atendio ", "Devolvio a", "Estado", "Observaciones", "Asignatura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PrestamosTabla);

        botonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ID Equipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Descripción:");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("TIPO:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ESTADO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("HORAS DE USO:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Fecha Ingreso:");

        campoFechaIngreso.setText("dd-mm-yyyy");
        campoFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaIngresoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Fecha Revision");

        campoRevision.setText("dd-mm-yyyy");

        botonBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrar.setText("Borrar Todo");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("HISTORIAL DE PRESTAMOS DE ESTE EQUIPO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(campoRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addComponent(botonBorrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoEquipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(botonConsultar)
                                                .addGap(64, 64, 64)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel5))
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoHorasUso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoTipo)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoEquipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoHorasUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(campoFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(botonBorrar)
                        .addComponent(botonVolver)))
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        frame.swap(1); // Hace el llamado al panel de administracion
    }//GEN-LAST:event_botonVolverActionPerformed

    private void campoFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaIngresoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        campoDescripcion.setText("");
        campoEquipoID.setText("");
        campoEstado.setText("");
        campoFechaIngreso.setText("dd-MM-yyyy");
        campoHorasUso.setText("");
        campoRevision.setText("dd-MM-yyyy");
        campoTipo.setText("");
        listaPrestamos.removeAll(listaPrestamos);
        llenarTablaPrestamos(listaPrestamos);
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        try{
            int codigoEquipo = Integer.parseInt(campoEquipoID.getText());
            Equipo equipo = equipoLogica.buscarEquipo(codigoEquipo);
            
            try{
                //equipo.getTipoEquipo().toString().charAt(0);
                //tipoComboBox.setSelectedItem(equipo.getTipoEquipo().toString());
                campoTipo.setText(equipo.getTipoEquipo().toString());
            }catch(Exception e){
                campoTipo.setText("NO IDENTIFICADO");
                //tipoComboBox.setSelectedItem("A");
            }
            campoHorasUso.setText(equipo.getHorasUso()+"");
            campoDescripcion.setText(equipo.getDescripcion());
            campoEstado.setText(equipo.getEstado());
            
            try{
                //equipo.getFechaIngreso().toString().charAt(0);
                SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd-MM-yyyy");
                String fecha = sdf.format(equipo.getFechaIngreso());
                campoFechaIngreso.setText(fecha);
            }catch(Exception e){
                campoFechaIngreso.setText("dd-MM-yyyy");
            }
            
            try{
                //equipo.getFechaRevision().toString().charAt(0);
                SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd-MM-yyyy");
                String fecha = sdf.format(equipo.getFechaUltimaRevision());
                campoRevision.setText(fecha);
            }catch(Exception e){
                campoRevision.setText("dd-MM-yyyy");
            }            

            listaPrestamos.removeAll(listaPrestamos);
            listaPrestamos = prestamoLogica.listarPrestamosporEquipo(equipo);
            llenarTablaPrestamos(listaPrestamos);
            
        }catch(Exception e){
            campoEquipoID.setText("");
            campoDescripcion.setText("");
            campoHorasUso.setText("");
            campoFechaIngreso.setText("dd-MM-yyyy");
            campoRevision.setText("dd-MM-yyyy");
        }
    }//GEN-LAST:event_botonConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrestamosTabla;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoEquipoID;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoFechaIngreso;
    private javax.swing.JTextField campoHorasUso;
    private javax.swing.JTextField campoRevision;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
