/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.EquipoLogica;
import logica.NotificacionEmail;
import logica.PrestamoLogica;
import logica.UsuarioLogica;
import modelo.Equipo;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class ConsultarPrestamosUsur extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarPrestamosUsur
     */
    vistaLogin frame;
    DefaultTableModel modelo;
    private Usuario usuario;
    private UsuarioLogica usuarioLogico;
    private Equipo equipo;
    private EquipoLogica equipoLogica;
    private Prestamo prestamo;
    private PrestamoLogica prestamoLogica;
    private List<Equipo> listaEquiposPrestados;
    private List<Prestamo> listaPrestamos;
    private NotificacionEmail notificacion;    
    
    public ConsultarPrestamosUsur(vistaLogin frame) {
        this.frame = frame;

        usuario = new Usuario();
        usuarioLogico = new UsuarioLogica();
        equipo = new Equipo(); 
        equipoLogica = new EquipoLogica();
        listaEquiposPrestados = new ArrayList<Equipo>();
        listaPrestamos = new ArrayList<Prestamo>();
       
        prestamoLogica = new PrestamoLogica();        
        
        initComponents();
        setBackground(Color.white);
    }

    public String getNombreAdministrador(){
        return frame.getAdministrador().getNombreAdmin();
    }

   public void llenarTablaPrestamos(List<Prestamo> listPrestamos){
        
        List<Prestamo> listaPres;
        listaPres = listPrestamos;
        setTabla(listaPres);
    }

    public void setTabla(List<Prestamo> prestamos){
        modelo =  (DefaultTableModel) PrestamosTabla.getModel();
        Date date = new Date();
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< prestamos.size();j++){
            aux = new String[12];
            aux[0] = String.valueOf(prestamos.get(j).getPrestamoID());
            aux[1] = String.valueOf(prestamos.get(j).getEquipoID().getEquipoID());
            aux[2] = prestamos.get(j).getEquipoID().getDescripcion();
            aux[3] = prestamos.get(j).getFechaEntrega().toString();
            aux[4] = prestamos.get(j).getHoraEntrega();
            try{
                aux[5] = prestamos.get(j).getFechaDevolucion().toString();
            }catch(Exception e){
                aux[5] = "No fecha";
            }
            aux[6] = prestamos.get(j).getHoraDevolucion();
            aux[7] = prestamos.get(j).getNombreMonitorAtendio();
            aux[8] = prestamos.get(j).getNombreMonitorDevolvio();
            aux[9] = prestamos.get(j).getEstadoPrestamo();
            aux[10] = prestamos.get(j).getObservaciones();
            aux[11] = prestamos.get(j).getAsignatura();
            modelo.addRow(aux);
        }
    }     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrestamosTabla = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoUsuarioID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        botonConsultarTodos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonConsultarPendientes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        campoCantidadPendientes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        botonNotificacion = new javax.swing.JButton();
        botonBorrarTodo = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("GIPLE V2.0 - LABORATORIO DE ELECTRÓNICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("CONSULTA DE PRESTAMOS DE USUARIO");

        PrestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Prestamo", "ID Equipo", "Nombre", "Fecha Entrega", "Hora Entrega", "Fecha Devol", "Hora Devol", "Atendio ", "Devolvio a", "Estado", "Observaciones", "Asignatura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PrestamosTabla);

        botonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ID USUARIO:");

        campoUsuarioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioIDActionPerformed(evt);
            }
        });
        campoUsuarioID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUsuarioIDKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("ID Corresponde a:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Consultar todos:");

        botonConsultarTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarTodos.setText("Consultar");
        botonConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarTodosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Consultar Pendientes:");

        botonConsultarPendientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarPendientes.setText("Consultar");
        botonConsultarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarPendientesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Cantidad de Elementos Pendientes:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Notificar via Email elementos pendientes:");

        botonNotificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNotificacion.setText("Enviar");
        botonNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNotificacionActionPerformed(evt);
            }
        });

        botonBorrarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrarTodo.setText("Borrar Todo");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34)
                                        .addComponent(botonBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(422, 422, 422))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonConsultarTodos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonConsultarPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(438, 438, 438)))
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoCantidadPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(botonConsultarTodos)
                    .addComponent(jLabel7)
                    .addComponent(botonConsultarPendientes)
                    .addComponent(jLabel8)
                    .addComponent(campoCantidadPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(botonNotificacion)
                    .addComponent(botonBorrarTodo)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        frame.swap(1); // hace el llamado al panel administrativo
    }//GEN-LAST:event_botonVolverActionPerformed

    private void campoUsuarioIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioIDKeyPressed
        if(evt.getKeyCode() == 10){
            int codigo = Integer.parseInt(campoUsuarioID.getText());
            usuario = usuarioLogico.buscarUsuario(codigo);
            campoUsuario.setText(usuario.getNombreUsuario()+" - "+usuario.getRol()+" - "+usuario.getProgramaAcademico()+" - Sem: "+usuario.getSemestre());
            
        }
    }//GEN-LAST:event_campoUsuarioIDKeyPressed

    private void campoUsuarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioIDActionPerformed

    private void botonConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarTodosActionPerformed
        listaPrestamos = prestamoLogica.listarPrestamosporUsuario(usuario);
        llenarTablaPrestamos(listaPrestamos);
    }//GEN-LAST:event_botonConsultarTodosActionPerformed

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed
        campoCantidadPendientes.setText("");
        campoUsuario.setText("");
        campoUsuarioID.setText("");
        listaPrestamos.removeAll(listaPrestamos);
        llenarTablaPrestamos(listaPrestamos);
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void botonConsultarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarPendientesActionPerformed
        listaPrestamos.removeAll(listaPrestamos);
        listaPrestamos = prestamoLogica.listarPrestamosporUsuarioPendientes(usuario);
        campoCantidadPendientes.setText(String.valueOf(listaPrestamos.size()));
        llenarTablaPrestamos(listaPrestamos);
        
    }//GEN-LAST:event_botonConsultarPendientesActionPerformed

    private void botonNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNotificacionActionPerformed
        listaPrestamos.removeAll(listaPrestamos);
        listaPrestamos = prestamoLogica.listarPrestamosporUsuarioPendientes(usuario);
        String mensaje = "Usted actualmente tiene pendiente por entregar los siguientes equipos: \n";
        mensaje = mensaje + "\n"; //agrego un segundo salto de linea
        for (Prestamo listaPrestamo : listaPrestamos) {
            mensaje = mensaje + listaPrestamo.getEquipoID().getEquipoID().toString() + " - " +listaPrestamo.getEquipoID().getDescripcion()+" - Entregado por - "+getNombreAdministrador()+ "\n";
        }
        notificacion = new NotificacionEmail(usuario);
        notificacion.setAsunto("Sistema GIPLE - Notificación de equipos pendientes");
        notificacion.setMensage(mensaje);
        notificacion.EnviarEmail();
        listaPrestamos.removeAll(listaPrestamos);
    }//GEN-LAST:event_botonNotificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrestamosTabla;
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonConsultarPendientes;
    private javax.swing.JButton botonConsultarTodos;
    private javax.swing.JButton botonNotificacion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoCantidadPendientes;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JTextField campoUsuarioID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
