/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import logica.AccesoLogica;
import logica.AdministradorLogica;
import logica.UsuarioLogica;
import modelo.Accesosistema;
import modelo.Administrador;

/**
 *
 * @author Usuario*/
public class LoginPanel extends javax.swing.JPanel {

    
    vistaLogin frame;
    public LoginPanel(vistaLogin frame) {
        this.frame = frame;
        initComponents();
        setBackground(Color.white);
    }
    
    public void borrarTodo(){
        campoLogin.setText("");
        campoPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoPassword = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        botonIngresoUsurGen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        labelLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLogin.setText("LOGIN:");

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPassword.setText("PASSWORD:");

        campoLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botonIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonIngresoUsurGen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonIngresoUsurGen.setText("Ingreso Usuario General");
        botonIngresoUsurGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoUsurGenActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("LABORATORIO DE ELECTRÓNICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("GESTION INTEGRAL DE PROCESOS LABORATORIO DE ELECTRÓNICA");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel3.setText("GIPLE V2.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLogin)
                            .addComponent(labelPassword))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(453, 453, 453))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonIngresoUsurGen, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(433, 433, 433))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogin)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword))
                .addGap(45, 45, 45)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(botonIngresoUsurGen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        AdministradorLogica administradorLogica = new AdministradorLogica();
        Accesosistema acceso = new Accesosistema();
        AccesoLogica accesoLogica = new AccesoLogica();
        Calendar calendario = new GregorianCalendar();
        try{
            Administrador adminEncontrado = administradorLogica.buscarAdmin(campoLogin.getText(),campoPassword.getText());
            if(adminEncontrado == null){
                JOptionPane.showMessageDialog(frame, "No se encontro el usuario");
            }
            else{
                //System.out.println("Si se encontro el administrador");
                frame.setAdministrador(adminEncontrado); // inicializo la sesion con el admin logueado
                // Aqui comienza a registrar el acceso al sistema
                acceso.setAdminID(adminEncontrado);
                acceso.setFecha(calendario.getTime());
                int hora = calendario.get(Calendar.HOUR_OF_DAY);
                int minutos = calendario.get(Calendar.MINUTE);
                acceso.setHoraIngreso(hora+":"+minutos);
                accesoLogica.registrarAcceso(acceso); // registra un acceso hecho al sistema
                frame.swap(1); // hago el llamado al panel administrador administrativo
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Excepcion Error");
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonIngresoUsurGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoUsurGenActionPerformed
        frame.swap(2); // hace el llamado al panel ingreso de usuarios
    }//GEN-LAST:event_botonIngresoUsurGenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonIngresoUsurGen;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    // End of variables declaration//GEN-END:variables
}
