/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.EquipoLogica;
import logica.NotificacionEmail;
import logica.PrestamoLogica;
import logica.UsuarioLogica;
import modelo.Equipo;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class RegistroDevolucionPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistroDevolucionPanel
     */
    vistaLogin frame;
    DefaultTableModel modelo;
    
    private Usuario usuario;
    private UsuarioLogica usuarioLogico;
    private Equipo equipo;
    private EquipoLogica equipoLogica;
    private Prestamo prestamo;
    private PrestamoLogica prestamoLogica;
    private List<Equipo> listaEquiposPrestados;
    private List<Prestamo> listaPrestamos;
    private SesionAdminAdministrativo sesion;
    private NotificacionEmail notificacion;
    
    public RegistroDevolucionPanel(vistaLogin frame) {
        this.frame = frame;
        
        usuario = new Usuario();
        usuarioLogico = new UsuarioLogica();
        equipo = new Equipo(); 
        equipoLogica = new EquipoLogica();
        listaEquiposPrestados = new ArrayList<Equipo>();
        listaPrestamos = new ArrayList<Prestamo>();
        prestamo = new Prestamo();
        prestamoLogica = new PrestamoLogica();
       
        initComponents();
        setBackground(Color.white);
    }
    
    public String getNombreAdministrador(){
        return frame.getAdministrador().getNombreAdmin();
    }
    
    public void llenarTablaPrestamos(List<Prestamo> listPrestamos){
        
        List<Prestamo> listaPres;
        listaPres = listPrestamos;
        setTabla(listaPres);
    }

    public void setTabla(List<Prestamo> prestamos){
        modelo =  (DefaultTableModel) PrestamosTabla.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< prestamos.size();j++){
            aux = new String[10];
            aux[0] = String.valueOf(prestamos.get(j).getEquipoID().getEquipoID());
            aux[1] = prestamos.get(j).getEquipoID().getDescripcion();
            aux[2] = prestamos.get(j).getFechaEntrega().toString();
            aux[3] = prestamos.get(j).getHoraEntrega();
            aux[4] = prestamos.get(j).getFechaEntrega().toString();
            aux[5] = prestamos.get(j).getHoraDevolucion();
            aux[6] = prestamos.get(j).getNombreMonitorAtendio();
            aux[7] = prestamos.get(j).getNombreMonitorDevolvio();
            aux[8] = prestamos.get(j).getObservaciones();
            aux[9] = prestamos.get(j).getEstadoPrestamo();
            modelo.addRow(aux);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoUsuarioID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoEquipoID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoDescripcionEquipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoObservaciones = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        botonBorrarTodo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrestamosTabla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("GIPLE V2.0 - LABORATORIO DE ELECTRÓNICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Registro de Devoluciones");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ID USUARIO:");

        campoUsuarioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioIDActionPerformed(evt);
            }
        });
        campoUsuarioID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUsuarioIDKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("ID corresponde a:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ID EQUIPO:");

        campoEquipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEquipoIDActionPerformed(evt);
            }
        });
        campoEquipoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoEquipoIDKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Observaciones: ");

        campoObservaciones.setText("Sin Observaciones");

        botonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonBorrarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrarTodo.setText("Borrar Todo");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });

        PrestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Equipo", "Nombre", "Fecha Entrega", "Hora Entrega", "Fecha Devol", "Hora Devol", "Entrego", "Recibio", "Obervaciones", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PrestamosTabla);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Elementos pendientes por el usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoEquipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel10)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoNombreUsuario)
                                            .addComponent(campoDescripcionEquipo)))
                                    .addComponent(campoObservaciones))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBorrarTodo)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(campoEquipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoDescripcionEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(campoObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonBorrarTodo)
                        .addGap(100, 100, 100)
                        .addComponent(botonVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        frame.swap(1); // hace el llamado al panel de administracion
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed
        campoDescripcionEquipo.setText("");
        campoEquipoID.setText("");
        campoNombreUsuario.setText("");
        campoObservaciones.setText("Sin Observaciones");
        campoUsuarioID.setText("");
        listaPrestamos.removeAll(listaPrestamos);
        llenarTablaPrestamos(listaPrestamos);
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void campoUsuarioIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            int codigo = Integer.parseInt(campoUsuarioID.getText());
            usuario = usuarioLogico.buscarUsuario(codigo);
            campoNombreUsuario.setText(usuario.getNombreUsuario()+" - "+usuario.getRol()+" - "+usuario.getProgramaAcademico());
            listaPrestamos.removeAll(listaPrestamos);
            listaPrestamos = prestamoLogica.listarPrestamosporUsuarioPendientes(usuario);
            llenarTablaPrestamos(listaPrestamos);
            
        }
    }//GEN-LAST:event_campoUsuarioIDKeyPressed

    private void campoEquipoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEquipoIDKeyPressed
        // TODO add your handling code here:
        prestamo = new Prestamo();
        int hora = 0;
        int minutos = 0; 
        Calendar calendario = new GregorianCalendar();
        
        if(evt.getKeyCode() == 10){
            int codigo = Integer.parseInt(campoEquipoID.getText());
            equipo = equipoLogica.buscarEquipo(codigo);
            campoDescripcionEquipo.setText(campoEquipoID.getText()+" - "+equipo.getDescripcion());
            boolean verificacion = prestamoLogica.verificaPrestamoEquipoToUsuario(equipo, usuario); // verifica que el equipo este prestado a ese usuario
            if(verificacion==true){ //hago la verificacion de que el usuario actualmente tiene el equipo prestado
                //JOptionPane.showMessageDialog(this, "El usuario tiene este equipo prestado");
                long idPrestamo = prestamoLogica.getIDPrestamo(equipo, usuario); // obtengo el id del prestamo
                prestamo = prestamoLogica.buscarPrestamo(idPrestamo); // Obtengo el prestamo
                prestamo.setEstadoPrestamo("ENTREGADO"); // Cambia el estado del prestamo indicando que el usuario devolvio el equipo
                prestamo.setNombreMonitorDevolvio(getNombreAdministrador()); // Indica a que administrador se le devolvio el equipo
                hora = calendario.get(Calendar.HOUR_OF_DAY);
                minutos = calendario.get(Calendar.MINUTE);
                prestamo.setFechaDevolucion(calendario.getTime());//Ajusta la fecha en la que devolvio el equipo
                prestamo.setHoraDevolucion(hora+":"+minutos); // Ajusta la hora en que devolvio el equipo
                prestamo.setObservaciones(prestamo.getObservaciones()+" - "+campoObservaciones.getText());//Ajusta las observaciones la momento de devolver el equipo
                
                try {
                    prestamoLogica.modificarPrestamo(prestamo);// Se ajusta el prestamo para cerrarlo completamente
                } catch (Exception ex) {
                    Logger.getLogger(RegistroDevolucionPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    equipoLogica.cambiarEstadoEquipopPrestamo(equipo); // Cambia el estado del equipo para ponerlo disponible nuevamente
                } catch (Exception ex) {
                    Logger.getLogger(RegistroDevolucionPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                campoEquipoID.setText("");
                //JOptionPane.showMessageDialog(this, "El equipo fue devuelto correctamente");
                notificacion = new NotificacionEmail(usuario);
                notificacion.setAsunto("Sistema GIPLE - Notificación de devolución");
                String mensaje = "Usted ha devuelto el equipo: "+equipo.getEquipoID()+" - "+equipo.getDescripcion()+" - Devuelto a - "+getNombreAdministrador();
                mensaje = mensaje + "\n";
                mensaje = mensaje + "\n";
                mensaje = mensaje + "El cuidado del laboratorio es responsabilidad de todos, su aporte en el cuidado de equipos y demás enseres, como tambien mantener las buenas costumbres, son importantes para asegurar la calidad y el bienestar de todos.";
                notificacion.setMensage(mensaje);
                notificacion.EnviarEmail();
                
                listaPrestamos.removeAll(listaPrestamos);
                listaPrestamos = prestamoLogica.listarPrestamosporUsuarioPendientes(usuario);
                llenarTablaPrestamos(listaPrestamos);                
                //listaPrestamos.add(prestamo);
                //llenarTablaPrestamos(listaPrestamos);
                
            }
            else{
                JOptionPane.showMessageDialog(this, "El usuario no tiene este equipo prestado");
            }
        }
    }//GEN-LAST:event_campoEquipoIDKeyPressed

    private void campoEquipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEquipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEquipoIDActionPerformed

    private void campoUsuarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrestamosTabla;
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoDescripcionEquipo;
    private javax.swing.JTextField campoEquipoID;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JTextField campoObservaciones;
    private javax.swing.JTextField campoUsuarioID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
