/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.Date;
import logica.AccesoLogica;
import modelo.Accesosistema;
import modelo.Administrador;
import modelo.Usuario;


/**
 *
 * @author Usuario
 */
public class SesionAdminAdministrativo extends javax.swing.JPanel {

    /**
     * Creates new form SesionAdminAdministrativo
     */
    vistaLogin frame;
    Administrador administrador;
    public SesionAdminAdministrativo(vistaLogin frame) {
        this.frame = frame;
        //frame.agregarPanel(1, this);
        //this.usuario = frame.getUsuario();
        initComponents();
        setBackground(Color.white);
        asignaturaComboBox.removeAllItems();
        asignaturaComboBox.addItem("PRACTICA LIBRE");
        asignaturaComboBox.addItem("INTRODUCCION A LA TECNOLOGIA ELECTRONICA");
        asignaturaComboBox.addItem("ELECTRICIDAD PARA ELECTRONICA");
        asignaturaComboBox.addItem("CALCULO I");
        asignaturaComboBox.addItem("CALCULO II");
        asignaturaComboBox.addItem("FISICA");
        asignaturaComboBox.addItem("ELECTRONICA BASICA");
        asignaturaComboBox.addItem("ALGORITMIA Y PROGRAMACION");
        asignaturaComboBox.addItem("TECNICAS DIGITALES");
        asignaturaComboBox.addItem("FUENTES Y AMPLIFICADORES");
        asignaturaComboBox.addItem("CIRCUITOS INTEGRADOS");
        asignaturaComboBox.addItem("MATEMATICAS ESPECIALES");
        asignaturaComboBox.addItem("MEDICIONES ELECTRONICAS");
        asignaturaComboBox.addItem("SISTEMAS ELECTROMECANICOS");
        asignaturaComboBox.addItem("MICROPROCESADORE I");
        asignaturaComboBox.addItem("MICROPROCESADORES II");
        asignaturaComboBox.addItem("SISTEMAS DE COMUNICACIONES");
        asignaturaComboBox.addItem("SISTEMAS AUTOMATICOS DE CONTROL");
        asignaturaComboBox.addItem("CONTROL ELECTRONICO DE POTENCIA");
        asignaturaComboBox.addItem("PLC");
        asignaturaComboBox.addItem("INTRUMENTACION ELECTRONICA");
        asignaturaComboBox.addItem("EXPERIMENTACION FISICA I");
        asignaturaComboBox.addItem("EXPERIMENTACION FISICA II");
        asignaturaComboBox.addItem("LAB FISICA GENERAL I");
        asignaturaComboBox.addItem("LAB FISICA GENERAL II");
    }
    
    public String getAsignatura(){
        return asignaturaComboBox.getSelectedItem().toString();
    }
    
    public Administrador getAdministrador(){
        return this.administrador;
    }
    
    public void setAdministrador(Administrador admin){
        this.administrador = admin;
        setNombreAdmin(administrador.getNombreAdmin());
        setTipoAdmin(administrador.getTipoAdmin());
    }
    
    public void setNombreAdmin(String nombre){
        campoNombre.setText(nombre);
        campoNombre.setEditable(false);
    }
    
    public void setTipoAdmin(String tipo){
        campoTipo.setText(tipo);
        campoTipo.setEditable(false);
    }
    
    public void setUltimoAccesoSistemaAdmin(Administrador Admin){
        AccesoLogica accesoLogica = new AccesoLogica();
        Accesosistema acceso = new Accesosistema();
        Date fecha = new Date();
        try{
            acceso = accesoLogica.ultimoAccesoSistema(Admin);
            fecha = acceso.getFecha();
            String horaIngreso = acceso.getHoraIngreso();
            campoFecha_Ult_Acceso.setText(fecha.toString()+" a las "+horaIngreso);
            campoFecha_Ult_Acceso.setEditable(false);
        }catch(Exception e){
            campoFecha_Ult_Acceso.setText("NO HA TENIDO UN ACCESO ANTERIOR");
            
        }
        
    }
    
    public void setOcultarBotones(Administrador Admin){
        if(Admin.getTipoAdmin().equals("MONITOR DE APOYO")){
            //botonModificarUsuario.setVisible(false);
            //botonRegistarModificarEquipo.setVisible(false);
        }
        else{
            //botonModificarUsuario.setVisible(true);
            //botonRegistarModificarEquipo.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonLogo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoFecha_Ult_Acceso = new javax.swing.JTextField();
        botonConsultarIngresoUsuario = new javax.swing.JButton();
        botonConsultarUsuario = new javax.swing.JButton();
        botonConsultaPrestamoUsuario = new javax.swing.JButton();
        ConsultarPrestamos = new javax.swing.JButton();
        botonRegistrarPrestamo = new javax.swing.JButton();
        botonRegistarDevolucion = new javax.swing.JButton();
        botonModificarUsuario = new javax.swing.JButton();
        botonConsultarEquipos = new javax.swing.JButton();
        botonListadoEquipos = new javax.swing.JButton();
        botonRegistarModificarEquipo = new javax.swing.JButton();
        botonConsultaIngresos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        asignaturaComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("GIPLE V2.0 - LABORATORIO DE ELECTRONICA UNIVERSIDAD DEL VALLE SEDE TULUA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Usted ha iniciado sesion como:");

        botonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-universidad-del-valle-2.png"))); // NOI18N
        botonLogo.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Su ultimo acceso al sistema fue:");

        botonConsultarIngresoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarIngresoUsuario.setText("Consultar Ingreso Usuario");
        botonConsultarIngresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarIngresoUsuarioActionPerformed(evt);
            }
        });

        botonConsultarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarUsuario.setText("Consultar Usuario");
        botonConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarUsuarioActionPerformed(evt);
            }
        });

        botonConsultaPrestamoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultaPrestamoUsuario.setText("Consultar Prestamos Usuario");
        botonConsultaPrestamoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaPrestamoUsuarioActionPerformed(evt);
            }
        });

        ConsultarPrestamos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConsultarPrestamos.setText("Consultar Prestamos General");
        ConsultarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPrestamosActionPerformed(evt);
            }
        });

        botonRegistrarPrestamo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonRegistrarPrestamo.setText("Registrar Prestamo");
        botonRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPrestamoActionPerformed(evt);
            }
        });

        botonRegistarDevolucion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonRegistarDevolucion.setText("Registar Devolucion");
        botonRegistarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistarDevolucionActionPerformed(evt);
            }
        });

        botonModificarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonModificarUsuario.setText("Registar/Modificar Usuario");
        botonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarUsuarioActionPerformed(evt);
            }
        });

        botonConsultarEquipos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultarEquipos.setText("Consultar Equipos");
        botonConsultarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarEquiposActionPerformed(evt);
            }
        });

        botonListadoEquipos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonListadoEquipos.setText("Ver Equipos");
        botonListadoEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoEquiposActionPerformed(evt);
            }
        });

        botonRegistarModificarEquipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonRegistarModificarEquipo.setText("Registar/Modificar Equipo");
        botonRegistarModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistarModificarEquipoActionPerformed(evt);
            }
        });

        botonConsultaIngresos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultaIngresos.setText("Consultar Ingresos General");
        botonConsultaIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaIngresosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Asignatura:");

        asignaturaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("INGRESOS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("USUARIOS");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("EQUIPOS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("PRESTAMOS");

        botonCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(255, 0, 51));
        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botonLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCerrarSesion))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoFecha_Ult_Acceso, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(asignaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultarIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultaIngresos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRegistarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegistrarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultaPrestamoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultarPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegistarModificarEquipo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonListadoEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonConsultarEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addGap(0, 369, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(138, 138, 138)
                .addComponent(jLabel11)
                .addGap(142, 142, 142)
                .addComponent(jLabel9)
                .addGap(417, 417, 417))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrarSesion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoFecha_Ult_Acceso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(asignaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultarIngresoUsuario)
                    .addComponent(botonConsultarUsuario)
                    .addComponent(botonConsultaPrestamoUsuario)
                    .addComponent(botonConsultarEquipos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonModificarUsuario)
                        .addComponent(botonConsultaIngresos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConsultarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonListadoEquipos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarPrestamo)
                    .addComponent(botonRegistarModificarEquipo))
                .addGap(18, 18, 18)
                .addComponent(botonRegistarDevolucion)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarIngresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarIngresoUsuarioActionPerformed
        frame.swap(3); // hace el llamado al panel de consulta de ingresos por usuario
    }//GEN-LAST:event_botonConsultarIngresoUsuarioActionPerformed

    private void botonConsultaIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaIngresosActionPerformed
        frame.swap(4); // hace el llamado al panel de consulta general de ingresos
    }//GEN-LAST:event_botonConsultaIngresosActionPerformed

    private void botonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarUsuarioActionPerformed
        frame.swap(5);
    }//GEN-LAST:event_botonModificarUsuarioActionPerformed

    private void botonConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarUsuarioActionPerformed
        frame.swap(6); // hace el llamado al panel de consulta de todos los usuarios
    }//GEN-LAST:event_botonConsultarUsuarioActionPerformed

    private void botonRegistarModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistarModificarEquipoActionPerformed
        frame.swap(7); // hace el llamado al panel de registrar y modificar equipos
    }//GEN-LAST:event_botonRegistarModificarEquipoActionPerformed

    private void botonConsultarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarEquiposActionPerformed
        frame.swap(8); // hace el llamado al panel de consultar equipos
    }//GEN-LAST:event_botonConsultarEquiposActionPerformed

    private void botonConsultaPrestamoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaPrestamoUsuarioActionPerformed
        frame.swap(9); // hace el llamado al panel de consulta de prestamos de usuario
    }//GEN-LAST:event_botonConsultaPrestamoUsuarioActionPerformed

    private void botonRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPrestamoActionPerformed
        frame.swap(10); // hace el llamado al panel de registrar un prestamo
    }//GEN-LAST:event_botonRegistrarPrestamoActionPerformed

    private void botonRegistarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistarDevolucionActionPerformed
        frame.swap(11); // hace el llamado al panel de registrar una devolucion
    }//GEN-LAST:event_botonRegistarDevolucionActionPerformed

    private void ConsultarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPrestamosActionPerformed
        frame.swap(12); // hace el llamado al panel de consultar los prestamos
    }//GEN-LAST:event_ConsultarPrestamosActionPerformed

    private void botonListadoEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoEquiposActionPerformed
         frame.swap(13); // hace el llamado al panel para ver los equipos
    }//GEN-LAST:event_botonListadoEquiposActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        frame.cerrarSesion();
        frame.swap(0); // hace el llamado al panel de logeo
    }//GEN-LAST:event_botonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarPrestamos;
    private javax.swing.JComboBox asignaturaComboBox;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonConsultaIngresos;
    private javax.swing.JButton botonConsultaPrestamoUsuario;
    private javax.swing.JButton botonConsultarEquipos;
    private javax.swing.JButton botonConsultarIngresoUsuario;
    private javax.swing.JButton botonConsultarUsuario;
    private javax.swing.JButton botonListadoEquipos;
    private javax.swing.JButton botonLogo;
    private javax.swing.JButton botonModificarUsuario;
    private javax.swing.JButton botonRegistarDevolucion;
    private javax.swing.JButton botonRegistarModificarEquipo;
    private javax.swing.JButton botonRegistrarPrestamo;
    private javax.swing.JTextField campoFecha_Ult_Acceso;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
